# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &development
  adapter: postgresql
  encoding: unicode
  database: ciderchain_dev
  pool: 5
  username: cider
  password: cider411

sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

development:
  <<: *sqlite

test:
  adapter: postgresql
  encoding: unicode
  database: ciderchain_test
  pool: 5
  username: cider
  password: cider411

production:
  host: ec2-54-221-201-165.compute-1.amazonaws.com
  database: dft95j990dk6fc
  username: dadolqhmwrbtrj
  password: wInORDcbRzQd7MmkqpqChie-kF
  port: 5432
  adapter: postgresql

